version: '3.8'

services:
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: airflow-dlt:latest
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    volumes:
      - airflow_db:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./job-dlt-pipeline:/opt/airflow/job-dlt-pipeline
      - ./dob_dbt_project:/opt/airflow/dags/dob_dbt_project

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: airflow-dlt:latest
    restart: always
    command: scheduler
    depends_on:
      - airflow-webserver
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    volumes:
      - airflow_db:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./job-dlt-pipeline:/opt/airflow/job-dlt-pipeline
      - ./dob_dbt_project:/opt/airflow/dags/dob_dbt_project
      - ./scripts:/opt/airflow/scripts

  metabase:
    image: metabase/metabase  
    platform: linux/amd64 
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./metabase-data:/metabase-data

volumes:
  airflow_db:
