default:
  outputs:
    dev:
      dbname: dev
      host: dobnamespace-workgroup.****.ap-southeast-1.redshift-serverless.amazonaws.com
      password: ******
      port: 5439
      schema: spectrum_schema
      threads: 4
      type: redshift
      user: **************
      method: database
  target: dev
